version: '3.8'

services:

  db:
    image: mysql:8.0.37-debian
    container_name: mysql_container
    restart: always
    cap_add:
      - SYS_NICE
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    logging:
        driver: loki
        options:
          loki-url: "http://localhost:3100/loki/api/v1/push"

  opendkim:
    build: ./opendkim
    container_name: opendkim_container
    environment:
      - OPENDKIM_DB_SERVER=${OPENDKIM_DB_SERVER}
      - OPENDKIM_DB_NAME=${OPENDKIM_DB_NAME}
      - OPENDKIM_DB_USER=${OPENDKIM_DB_USER}
      - OPENDKIM_DB_PASS=${OPENDKIM_DB_PASS}
    #   TZ: ${TZ:-UTC}
    ports:
      - "8891:8891"
    command: ["/entrypoint.sh"]
   
    depends_on:
      - db

  policyd:
    build: ./policyd
    container_name: policyd_container
    environment:
      - POLICYD_DB_SERVER=${POLICYD_DB_SERVER}
      - POLICYD_DB_NAME=${POLICYD_DB_NAME}
      - POLICYD_DB_USER=${POLICYD_DB_USER}
      - POLICYD_DB_PASS=${POLICYD_DB_PASS}
    ports:
      - "10031:10031"
    command: ["/entrypoint.sh"]

    depends_on:
      - db